package org.tempuri;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-09-22T19:28:26.524-03:00
 * Generated source version: 4.0.5
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IServicoCalculadora")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class})
public interface IServicoCalculadora {

    @WebMethod(operationName = "Soma", action = "http://tempuri.org/IServicoCalculadora/Soma")
    @Action(input = "http://tempuri.org/IServicoCalculadora/Soma", output = "http://tempuri.org/IServicoCalculadora/SomaResponse")
    @RequestWrapper(localName = "Soma", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Soma")
    @ResponseWrapper(localName = "SomaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SomaResponse")
    @WebResult(name = "SomaResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Long soma(

        @WebParam(name = "x", targetNamespace = "http://tempuri.org/")
        java.lang.Long x,
        @WebParam(name = "y", targetNamespace = "http://tempuri.org/")
        java.lang.Long y
    );
}
